### ISSUE TITLE
Set default values in the MetropolisHastings builder

### ISSUE THREAD

**Issue by mhutti1** [improbable-research/keanu#164]
**Is your feature request related to a problem? Please describe.**
When creating a new instance of MetropolisHastings via ```MetropolisHastings.builder()```. All of the options must be set by the user or else they will be null. This means that for example you must call ```.random(new KeanuRandom())``` or else crash with a null pointer when attempting to sample.

```
Exception in thread "main" java.lang.NullPointerException
	at io.improbable.keanu.distributions.continuous.Triangular.sample(Triangular.java:26)
	at io.improbable.keanu.distributions.continuous.Triangular.sample(Triangular.java:8)
	at io.improbable.keanu.vertices.dbl.probabilistic.TriangularVertex.sample(TriangularVertex.java:117)
	at io.improbable.keanu.vertices.dbl.probabilistic.TriangularVertex.sample(TriangularVertex.java:14)
	at io.improbable.irsim.TreeProposal.setFor(TreeProposal.java:26)
	at io.improbable.irsim.TreeProposal.getProposal(TreeProposal.java:15)
	at io.improbable.keanu.algorithms.mcmc.MetropolisHastingsStep.step(MetropolisHastingsStep.java:74)
	at io.improbable.keanu.algorithms.mcmc.MetropolisHastingsStep.step(MetropolisHastingsStep.java:53)
	at io.improbable.keanu.algorithms.mcmc.MetropolisHastings.getPosteriorSamples(MetropolisHastings.java:71)
	at io.improbable.irsim.RoadBinaryParser.complete(RoadBinaryParser.java:137)
	at org.openstreetmap.osmosis.osmbinary.file.BlockInputStream.process(BlockInputStream.java:37)
	at io.improbable.irsim.IRSim.main(IRSim.java:29)
```

**Describe the solution you'd like**
Default values should be used so things such as a KeanuRandom() do not have to be passed in if not required.

**Describe alternatives you've considered**
An alternative solution might be to make the default configs settings mutable.

**Comment by christophernorth** [comment]
Fixed by #172
