### ISSUE TITLE
Py4JException when calling Keanu methods in python

### ISSUE THREAD

**Issue by johannespetrat** [improbable-research/keanu#375]
**Describe the bug**
I can import keanu-python, but Py4J throws an error whenever I call a keanu method.
Stacktrace:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/johannespetrat/anaconda2/envs/py37/lib/python3.7/site-packages/keanu/vertex/generated.py", line 162, in ConstantDouble
    return Double(context.jvm_view().ConstantDoubleVertex, constant)
  File "/Users/johannespetrat/anaconda2/envs/py37/lib/python3.7/site-packages/keanu/vertex/base.py", line 21, in __init__
    val = ctor(*(Vertex.__parse_args(args)))
  File "/Users/johannespetrat/anaconda2/envs/py37/lib/python3.7/site-packages/py4j/java_gateway.py", line 1554, in __call__
    answer, self._gateway_client, None, self._fqn)
  File "/Users/johannespetrat/anaconda2/envs/py37/lib/python3.7/site-packages/py4j/protocol.py", line 332, in get_return_value
    format(target_id, ".", name, value))
py4j.protocol.Py4JError: An error occurred while calling None.io.improbable.keanu.vertices.dbl.nonprobabilistic.ConstantDoubleVertex. Trace:
py4j.Py4JException: Constructor io.improbable.keanu.vertices.dbl.nonprobabilistic.ConstantDoubleVertex([class io.improbable.keanu.vertices.dbl.nonprobabilistic.ConstantDoubleVertex]) does not exist
	at py4j.reflection.ReflectionEngine.getConstructor(ReflectionEngine.java:179)
	at py4j.reflection.ReflectionEngine.getConstructor(ReflectionEngine.java:196)
	at py4j.Gateway.invoke(Gateway.java:237)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a conda environment with python 3.7.0
2. Run `pip install keanu`
3. Open the python shell
4. Run `import keanu`
5. Run `keanu.vertext.ConstantDouble(1.)`

**Expected behavior**
This should create a `ConstantDoubleVertex`.

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Python 3.7.0
- Anaconda 4.4.10

**Comment by migwellian** [comment]
Hi Johannes, it works when you use `Const` instead of `ConstDouble` (the double type is inferred). We'll look into why it fails with `ConstDouble` and make a fix.

**Comment by johannespetrat** [comment]
Cool, thanks a lot for clarifying this!
